FROM ubuntu:22.10


# sed -i -e 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories && \
# -- install ossutil

RUN \
 sed -i \
  -e 's/security.ubuntu.com/mirrors.aliyun.com/g' \
  -e 's/archive.ubuntu.com/mirrors.aliyun.com/g' \
  /etc/apt/sources.list && \
 apt-get update -y && apt-get upgrade -y && \
 apt-get install -y git curl python3 ffmpeg python3-pip vim \
  s3fs rsync rclone && \
 apt-get clean all

RUN --mount=type=bind,source=setup/ffmpeg,target=/setup \
 curl -s -o /usr/bin/ossutil https://gosspublic.alicdn.com/ossutil/1.7.7/ossutil64 && \
 chmod a+x /usr/bin/ossutil && \
 /setup/pip
 

