#!/bin/sh

cat <<EOF > /etc/pip.conf
[global]
#index-url=http://mirrors.aliyun.com/pypi/simple/
#trusted-host=mirrors.aliyun.com
index-url=https://pypi.tuna.tsinghua.edu.cn/simple/
trusted-host=pypi.tuna.tsinghua.edu.cn
EOF

pip install \
 ffmpeg-python opencv-python pillow oss2 fabric

